---
etcd:
  image: quay.io/coreos/etcd:v2.0.8
  ports:
  - "2379:2379"
  - "2380:2380"
  - "4001:4001"
  environment:
    ETCD_NAME: deconst1
    HostIP: 172.17.42.1
    ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
    ETCD_ADVERTISE_CLIENT_URLS: http://172.17.42.1:2379
    ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
    ETCD_INITIAL_ADVERTISE_PEER_URLS: http://172.17.42.1:2380
    ETCD_INITIAL_CLUSTER: deconst1=http://172.17.42.1:2380
mongo:
  image: mongo:2.6
content:
  image: quay.io/deconst/content-service
  links:
  - "mongo:mongo"
  environment:
    RACKSPACE_USERNAME:
    RACKSPACE_APIKEY:
    RACKSPACE_REGION: DFW
    ADMIN_APIKEY: "12345"
    CONTENT_CONTAINER: deconst-drc-content
    ASSET_CONTAINER: deconst-drc-assets
    MONGODB_URL: mongodb://mongo:27017/content
    CONTENT_LOG_LEVEL: DEBUG
  ports:
  - "9000:8080"
mapping:
  image: quay.io/deconst/mapping-service
  environment:
    CONTROL_REPO_URL: /data/control-repo
    MAP_LOG_LEVEL: DEBUG
  ports:
  - "9001:8080"
  volumes:
  - .:/data/control-repo:ro
layout:
  image: quay.io/deconst/layout-service
  environment:
    CONTROL_REPO_URL: /data/control-repo
    LAYOUT_LOG_LEVEL: DEBUG
  ports:
  - "9002:8080"
  volumes:
  - .:/data/control-repo:ro
webhook:
  image: quay.io/deconst/webhook-service
  links:
  - etcd
  environment:
    ETCD_URL: etcd
    CONTROL_REPO_TOKEN:
  ports:
  - "9003:8080"
etcdwatcher:
  image: quay.io/deconst/etcd-watcher
  ports:
  - "9004:2379"
  links:
  - etcd
  - mapping
  - layout
  environment:
    MAPPING_SERVICE_URL: http://mapping:8080/
    LAYOUT_SERVICE_URL: http://layout:8080/
presenter:
  image: quay.io/deconst/presenter
  links:
  - content
  - mapping
  - layout
  environment:
    CONTENT_SERVICE_URL: http://content:8080/
    MAPPING_SERVICE_URL: http://mapping:8080/
    LAYOUT_SERVICE_URL: http://layout:8080/
    PRESENTED_URL_DOMAIN: developer.rackspace.com
    PUBLIC_URL_DOMAIN: docker
    PUBLIC_URL_PROTO: http
    PRESENTER_LOG_LEVEL: DEBUG
  ports:
  - "80:8080"
